# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      # - image: korekontrol/ubuntu-java-python2
      # - image: circleci/python:2.7.15-jessie
      - image: rappdw/docker-java-python
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/dvpwa

    steps:
      - checkout
      - run: 
          name: install dependencies
          command: | 
            #sudo apt install -y python-software-properties
            #add-apt-repository ppa:webupd8team/java
            #apt update -y
            #apt install oracle-java8-installer -y
            #apt install oracle-java8-set-default 
            #apt-get update
            #apt-get install libcurl3 php5-curl
            #apt-get install curl -y
            #pip install --upgrade pip setuptools wheel 
            #python -m virtualenv flask
            #source flask/bin/activate
            #pip install flask
            #pip install -r requirements.txt
             python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            #bash <(curl -s https://scripts.scantist.com/ci-travis.sh)
            bash <(curl -s https://scripts.scantist.com/staging/ci-circle-jar.sh)
